import './globals.css'
import {Inter} from 'next/font/google'
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import NextjsTopLoader from 'nextjs-toploader';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Game Nexus',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${inter.className} overflow-x-hidden`}>
        <NextjsTopLoader />
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
